### ISSUE TITLE
Updating Peertube 3.3.0. to 3.4.0. (Docker) breaks Videos [was: Embedded player broken on 3.4.0]

### ISSUE THREAD

**Issue by tilllt** [Chocobozzz/PeerTube#4403]
**Describe the current behavior**
iFrame-Embedded Peertube videos from a Peertube Server Running 3.4.0. show as "Sorry, the player is not compatible with your web browser. Please try the latest Firefox Version" - independently of the OS and Browser and Version. 

**Steps to reproduce:**

1.https://tinkthank.de/worksample/emmanuelle-charpentier
2. open link from 1. which was working with Peertube 3.0.3

**Describe the expected behavior**
iFrame embedded Videos should play without Error.

**Additional information**
Javascript Error Message from Console
```
annot init embed. TypeError: p.getItem is not a function
    at Function.load (video-embed.cb94f3ad1d26ba89f80c.bundle.js:2)
    at Ae.<anonymous> (video-embed.cb94f3ad1d26ba89f80c.bundle.js:2)
    at Generator.next (<anonymous>)
    at video-embed.cb94f3ad1d26ba89f80c.bundle.js:2
    at new Promise (<anonymous>)
    at r (video-embed.cb94f3ad1d26ba89f80c.bundle.js:2)
    at Ae.init (video-embed.cb94f3ad1d26ba89f80c.bundle.js:2)
    at Function.<anonymous> (video-embed.cb94f3ad1d26ba89f80c.bundle.js:2)
    at Generator.next (<anonymous>)
    at video-embed.cb94f3ad1d26ba89f80c.bundle.js:2
(anonymous) @ video-embed.cb94f3ad1d26ba89f80c.bundle.js:2 
```

* PeerTube instance:
  * URL: two.pixelscope.de
  * version: 3.4.0 / Docker

* Browser name, version and platforms on which you could reproduce the bug: Windows 10 / Linux / etc

**Comment by Chocobozzz** [comment]
Hello,

You please use the share modal for appropriate iframe options. They must be something like

```
<iframe width="560" height="315" sandbox="allow-same-origin allow-scripts allow-popups" src="https://..." frameborder="0" allowfullscreen></iframe>
```

**Comment by tilllt** [comment]
Just to understand, was there a change between 3.0.3 and 3.0.4 in the way the videos need to be embedded, because the embeds worked just fine with 3.0.3?

**Comment by tilllt** [comment]
```
<iframe width="100%" height="100%" sandbox="allow-scripts allow-popups"
                src="{{ record.media.url }}{{ record.media_params }}" frameborder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowfullscreen></iframe>
```

This is the actual embed, in case of the embed URL discussed here, the twig variables "{{ record.media.url }}{{ record.media_params }}" translates to: 
[](https://two.pixelscope.de/videos/embed/0a1c6b87-be0c-4e1d-8c93-3ef4aa101580?start=1m57&title=false&subtitle=false&controls=true&warningTitle=0&autoplay=1&peertubeLink=0)

**Comment by Chocobozzz** [comment]
Please try to update `sandbox` attribute to `sandbox="allow-same-origin allow-scripts allow-popups"`

**Comment by tilllt** [comment]
This made the error message disappear but the video doesnt play, keeps "buffering" forever...
There are several errors in the Console (deleted the irrelevant ones)...

´´´
video-embed.cb94f3ad1d26ba89f80c.bundle.js:2 Loading script /plugins/video-annotation/0.0.5/client-scripts/dist/embed-client-plugin.js of plugin video-annotation.
two.pixelscope.de/static/streaming-playlists/hls/0a1c6b87-be0c-4e1d-8c93-3ef4aa101580/segments-sha256.json:1 Failed to load resource: the server responded with a status of 404 (Not Found)
video-embed.cb94f3ad1d26ba89f80c.bundle.js:2 Running hook action:embed.player.loaded of plugin video-annotation.
two.pixelscope.de/static/streaming-playlists/hls/0a1c6b87-be0c-4e1d-8c93-3ef4aa101580/master.m3u8:1 Failed to load resource: the server responded with a status of 404 (Not Found)
586.d1db63762279715dc448.chunk.js:1 HLS.js error: networkError - fatal: true - manifestLoadError
_onError @ 586.d1db63762279715dc448.chunk.js:1
586.d1db63762279715dc448.chunk.js:1 trying to recover network error
´´´

**Comment by Chocobozzz** [comment]
The source video is broken: https://two.pixelscope.de/w/2fq8mbqXno8ykbmdrgeUDW

**Comment by tilllt** [comment]
The source video was uploaded approximately 13 days ago to the same instance, at the time running peertube 3.0.3 ... it was embedded from there and running fine.

I am running an auto updater for my docker container, so peertube automatically was updated to 3.0.4. since that moment, it doesn't play anymore and as you say "is broken"...

So to make it short: if it's broken, peertube broke it. How can I fix it?

**Comment by Chocobozzz** [comment]
Do you follow the upgrade guide? https://docs.joinpeertube.org/install-docker?id=upgrade

What is the `storage` value of `docker-volume/config/production.yaml`?

**Comment by tilllt** [comment]
Thanks, maybe that was the issue:
  streaming_playlists: '../data/streaming-playlists'
was missing from the production.yaml

A Question: How do i recreate the playlists for all videos on this instance?

And to answer your question: i didnt not read the docker update instructions, since i am running 40+ containers and therefore use Ouroboros to auto update them. I would appreciate if potentially "breaking" config changes are introduced, like new (apparently essential) config options, if Peertube would refuse to start and not do business as usual... 

Also, what is the technical reason that we cannot define a base "data" directory and peertube can create whatever it wants in there (and docker can bind it to a local path). The seperate  storage paths would then just be an optional thing if you are using storage outside of the default path ? That would prevent this type of problems from happening...

**Comment by Chocobozzz** [comment]
> if Peertube would refuse to start and not do business as usual...

We add breaking changes/new configuration keys in the changelog, that you must read on update. You can try to recover playlist files from old container.

Or try https://docs.joinpeertube.org/maintain-tools?id=create-transcoding-jobjs

**Comment by tilllt** [comment]
I don't see a way in the docs to recreate ALL HLS Playlists, just for a single video. Is there at least a command to list all videoUUID of clips on the local instance to make this somehow scriptable?

**Comment by JigmeDatse** [comment]
I'm not sure where this is broken, but the JoinPeertube site displays this...

It seems at least to some level related to this issue.

![Screenshot_20210921_210452](https://user-images.githubusercontent.com/66363/134282043-ac475ef2-aeb4-45c3-bc02-f7aa49cc8fc1.png)

**Comment by tilllt** [comment]
Maybe somebody forgot to read the docker upgrade instructions.

**Comment by JigmeDatse** [comment]
I wasn't sure where the video was coming from.  It's the framasoft site, so...  I don't know.  Possibly the wrong embed code?  I do find it... amusing/confusing/whatever (not sure what to call it) when the official site ends up not working.  I also feel that this just should be fixed.  Preferably in a way that ends up not being fragile in the future.

**Comment by tilllt** [comment]
That was precisely my wish: 

- a default storage folder that is on a docker bind volume so all relevant data volumes (even the ones defined in future config files) are always persistent
- or, a command to recreate ALL HLS Playlists, if the data is lost
- or the Peertube docker not starting if there are breaking config changes that need to be resolved if otherwise the lead to a broken installation.

But i don't think @Chocobozzz considers any of those ideas something to think about because: you should read the docker upgrade instructions, so there we go.
