### ISSUE TITLE
There are errors when use https

### ISSUE THREAD

**Issue by imtube** [Chocobozzz/PeerTube#37]
When I use https to visit the website, the browser console said 
`Fetch API cannot load http://aaa.com/static/torrents/fa099e4a-df7e-4165-b733-99ad00c5ebcc.torrent. Redirect from 'http://aaa.com/static/torrents/fa099e4a-df7e-4165-b733-99ad00c5ebcc.torrent' to 'https://aaa.com/static/torrents/fa099e4a-df7e-4165-b733-99ad00c5ebcc.torrent' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://aaa.com' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by imtube** [comment]
@Chocobozzz 
I know what's happening, but I don't know how to fix it, please help me.
The browser console said
`webtorrent.min.js:7 Mixed Content: The page at 'https://aaa.com/videos/watch/aaa' was loaded over HTTPS, but requested an insecure resource 'http://aaa.com/static/torrents/aaa.torrent'. This content should also be served over HTTPS.`

I have set production.yaml to this:
```
webserver:
  https: true
  hostname: 'aaa.com'
  port: 443
```
But it still shows the same error.

**Comment by imtube** [comment]
@Chocobozzz I restarted the server and can watch the video now, but there are still the same errors in the browser console, I checked your demo website, and there is no errors.

**Comment by Chocobozzz** [comment]
It seems you uploaded the video when your server was in HTTP and then you changed the webserver configuration for using HTTPS.

PeerTube needs to regenerate the torrent files. You can use the [update-host](https://github.com/Chocobozzz/PeerTube/blob/develop/scripts/update-host.js) script for that purpose.

`NODE_ENV=production npm run update-host`

**Comment by imtube** [comment]
@Chocobozzz Thank you, I have updated the script, but there is still the same error, and I can't upload video now, the browser console says
`Failed to load resource: https://aaa.com/api/v1/videos
the server responded with a status of 401 (Unauthorized)`

**Comment by imtube** [comment]
Is there any way to uninstall peertube ? I can reinstall it and test the https

**Comment by Chocobozzz** [comment]
Yes, `npm run danger:clean:prod`.

**Comment by imtube** [comment]
@Chocobozzz Thank you very much! it's completely no problem now!

**Comment by shahzaib414** [comment]
When i upload Video File . Server Console Gives me Error 
" typeerror: cannot convert object to primitive value.
Is Video File "

**Comment by Chocobozzz** [comment]
The server is from the latest commit of the develop branch?

**Comment by shahzaib414** [comment]
Yess.
Can you guide me?

**Comment by Chocobozzz** [comment]
Paste the server logs **and** your HTTP request on pastebin please.

**Comment by shahzaib414** [comment]
Shahzaib.shahid414@gmail.com
Please email me. So that i can ping you i am out of station for an hour

**Comment by shahzaib414** [comment]
here is Error  when i try to upload  Video
error: [62.210.77.240:80]  TypeError: Cannot convert object to primitive value
    at String.replace (<anonymous>)
    at /home/peertube/PeerTube/node_modules/express-validator/lib/express_valida                                                                                                             tor.js:473:49
    at Array.forEach (native)
    at ValidatorChain.isVideoFile (/home/peertube/PeerTube/node_modules/express-                                                                                                             validator/lib/express_validator.js:473:12)
    at videosAdd (/home/peertube/PeerTube/server/middlewares/validators/videos.j                                                                                                             s:24:58)
    at Layer.handle [as handle_request] (/home/peertube/PeerTube/node_modules/ex                                                                                                             press/lib/router/layer.js:95:5)
    at next (/home/peertube/PeerTube/node_modules/express/lib/router/route.js:13                                                                                                             7:13)
    at Immediate._onImmediate (/home/peertube/PeerTube/node_modules/multer/lib/m                                                                                                             ake-middleware.js:53:37)
    at runCallback (timers.js:804:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
info: [62.210.77.240:80] ::ffff:62.210.77.240 - - [29/Jun/2017:13:13:37 +0000] "                                                                                                             POST /api/v1/videos HTTP/1.0" 500 21 "https://62.210.77.240/videos/add" "Mozilla                                                                                                             /5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome                                                                                                             /59.0.3071.115 Safari/537.36"

**Comment by shahzaib414** [comment]
when i tried to run command in latest  branch it failed at npm run build 
Error: Cannot find module '/home/PeerTube/run'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! peertube@0.0.1 build: `npm run build:client:prod`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the peertube@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-06-29T13_54_03_762Z-debug.log

**Comment by Dryusdan** [comment]
I encounter the same problem.
PeerTube isn't compatible with nodejs 8, but work with nodejs 6.11 ;)

**Comment by shahzaib414** [comment]
So which branch code you use?of peer tube

**Comment by Dryusdan** [comment]
I use peertube master, with nginx 1.13, libressl 2.5.4, nodejs 6.11 on alpine system (Docker)

**Comment by shahzaib414** [comment]
Can we use without docker. Which git branch is  stable

**Comment by shahzaib414** [comment]
i successfully uploaded now i am facing this error 
polyfills.2272bcc….bundle.js:1 Mixed Content: The page at 'https://62.210.77.240/videos/watch/c4e66a5e-72be-4c19-9187-d1d802ed1156' was loaded over HTTPS, but requested an insecure resource 'http://62.210.77.240/static/torrents/c4e66a5e-72be-4c19-9187-d1d802ed1156.torrent'. This request has been blocked; the content must be served over HTTPS

**Comment by Dryusdan** [comment]
Browser security... You call a video in http but you display your page in https
Do you update `config/default.yml` and set https ?

**Comment by shahzaib414** [comment]
yes when i enable https  in config i failed to  run NODE_ENV=production npm start

**Comment by shahzaib414** [comment]
now i am facing Error 502 Bad Gateway

 Here is my config/default.yml

listen:
  port: 9000

webserver:
  https: false
  hostname: 'localhost'
  port: 9000

# Your database name will be "peertube"+database.suffix
database:
  hostname: 'localhost'
  port: 5432
  suffix: '_dev'
  username: 'peertube'
  password: 'peertube'

# From the project root directory
storage:
  certs: 'certs/'
  videos: 'videos/'
  logs: 'logs/'
  previews: 'previews/'
  thumbnails: 'thumbnails/'
  torrents: 'torrents/'

admin:
  email: 'admin@example.com'

signup:
  enabled: false
and  vim /etc/nginx/sites-available/peertube
server {
  listen 80;
  # listen [::]:80;
  server_name 62.210.77.240;
  rewrite ^ https://$server_name$request_uri? permanent;
}

server {
  listen 443 ssl spdy; # or http2
  # listen [::]:443;
  server_name 62.210.77.240;

  # For example with Let's Encrypt
  ssl_certificate      /etc/nginx/ssl/nginx.crt;
  ssl_certificate_key  /etc/nginx/ssl/nginx.key;
  # ssl_trusted_certificate /etc/letsencrypt/live/domain.tld/chain.pem;

  location / {
    proxy_pass https://62.210.77.240:9000;

**Comment by Dryusdan** [comment]
> https: false

set to true

**Comment by shahzaib414** [comment]
should i need to change port to 443 ? or just  set true https
because i changed port also to 443 now i am facing error: [62.210.77.240:443] uncaughtException: listen EADDRINUSE :::9000
{ date: 'Fri Jun 30 2017 10:04:56 GMT+0200 (CEST)',
 as  i restart server checked port is free and when i run production i face this error

**Comment by Dryusdan** [comment]
Yes, else peertube call https://xxx:80 and your nginx serveur dislike it so it kill connexion

**Comment by shahzaib414** [comment]
nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled)
   Active: active (running) (Result: exit-code) since Fri 2017-06-30 10:12:56 CEST; 23min ago
  Process: 4685 ExecReload=/usr/sbin/nginx -g daemon on; master_process on; -s reload (code=exited, stat        us=0/SUCCESS)
  Process: 557 ExecStart=/usr/sbin/nginx -g daemon on; master_process on; (code=exited, status=0/SUCCESS        )
  Process: 502 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=        0/SUCCESS)
 Main PID: 558 (nginx)
   CGroup: /system.slice/nginx.service
           ├─ 558 nginx: master process /usr/sbin/nginx -g daemon on; master_process on;
           ├─4687 nginx: worker process
           ├─4688 nginx: worker process
           ├─4689 nginx: worker process
           └─4690 nginx: worker process

Jun 30 10:25:10 peertube systemd[1]: Reloading A high performance web server and a reverse proxy server.
Jun 30 10:25:10 peertube nginx[2819]: nginx: [emerg] SSL_CTX_use_PrivateKey_file("/etc/nginx/ssl/...lib)
Jun 30 10:25:10 peertube systemd[1]: nginx.service: control process exited, code=exited status=1
Jun 30 10:25:10 peertube systemd[1]: Reload failed for A high performance web server and a revers...ver.
Jun 30 10:28:01 peertube systemd[1]: Reloading A high performance web server and a reverse proxy server.
Jun 30 10:28:01 peertube systemd[1]: Reloaded A high performance web server and a reverse proxy server.
Jun 30 10:28:18 peertube systemd[1]: Reloading A high performance web server and a reverse proxy server.
Jun 30 10:28:18 peertube systemd[1]: Reloaded A high performance web server and a reverse proxy server.
Jun 30 10:35:55 peertube systemd[1]: Reloading A high performance web server and a reverse proxy server.
Jun 30 10:35:55 peertube systemd[1]: Reloaded A high performance web server and a reverse proxy server.
Hint: Some lines were ellipsized, use -l to show in full.


 facing nginx server error

**Comment by shahzaib414** [comment]
hey i resolved web Server Error  but i am  facing still that error 
here is my file 
server {
  listen 80;
  # listen [::]:80;
  server_name 62.210.77.240;
  rewrite ^ https://$server_name$request_uri? permanent;
}

server {
  listen 443 ssl spdy; # or http2
  # listen [::]:443;
  server_name 62.210.77.240;

  # For example with Let's Encrypt
  ssl_certificate      /etc/nginx/ssl/nginx.crt;
  ssl_certificate_key  /etc/nginx/ssl/nginx.key;
  # ssl_trusted_certificate /etc/letsencrypt/live/domain.tld/chain.pem;

  location / {
    proxy_pass http://62.210.77.240:9000;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    # For the video upload
    client_max_body_size 100m;
  }

  # Bypass PeerTube webseed route for better performances
  location /static/webseed {
    if ($request_method = 'OPTIONS') {
      add_header 'Access-Control-Allow-Origin' '*';
      add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
      add_header 'Access-Control-Allow-Headers' 'Range,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
      add_header 'Access-Control-Max-Age' 1728000;
      add_header 'Content-Type' 'text/plain charset=UTF-8';
      add_header 'Content-Length' 0;
      return 204;
    }

    if ($request_method = 'GET') {
      add_header 'Access-Control-Allow-Origin' '*';
      add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
      add_header 'Access-Control-Allow-Headers' 'Range,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
    }
 # For the video upload
    client_max_body_size 100m;
  }

  # Bypass PeerTube webseed route for better performances
  location /static/webseed {
    if ($request_method = 'OPTIONS') {
      add_header 'Access-Control-Allow-Origin' '*';
      add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
      add_header 'Access-Control-Allow-Headers' 'Range,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
      add_header 'Access-Control-Max-Age' 1728000;
      add_header 'Content-Type' 'text/plain charset=UTF-8';
      add_header 'Content-Length' 0;
      return 204;
    }

    if ($request_method = 'GET') {
      add_header 'Access-Control-Allow-Origin' '*';
      add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
      add_header 'Access-Control-Allow-Headers' 'Range,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
    }

    alias /home/PeerTube/videos;
  }

  # Websocket tracker
  location /tracker/socket {
    # Peers send a message to the tracker every 15 minutes
    # Don't close the websocket before this time
    proxy_read_timeout 1200s;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_http_version 1.1;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $host;
    proxy_pass http://62.210.77.240:9000;
  }
}

**Comment by shahzaib414** [comment]
Hey its seems funny but i am  able to successfully load server but now when i try to play video it shows 

webtorrent.min.js:7 WebSocket connection to 'wss://62.210.77.240:80/tracker/socket' failed: Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR
r @ webtorrent.min.js:7
r._openSocket @ webtorrent.min.js:2
r @ webtorrent.min.js:2
(anonymous) @ webtorrent.min.js:2
r @ webtorrent.min.js:2
r._createTracker @ webtorrent.min.js:8
r @ webtorrent.min.js:8
o._onListening @ webtorrent.min.js:1
o._onParsedTorrent @ webtorrent.min.js:1
(anonymous) @ webtorrent.min.js:1
c.run @ webtorrent.min.js:5
u @ webtorrent.min.js:5
webtorrent.min.js:7 WebSocket connection to 'wss://62.210.77.240:80/tracker/socket' failed: Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR
r @ webtorrent.min.js:7
r._openSocket @ webtorrent.min.js:2
(anonymous) @ webtorrent.min.js:2
n.invokeTask @ polyfills.2272bcc….bundle.js:1
t.runTask @ polyfills.2272bcc….bundle.js:1
invoke @ polyfills.2272bcc….bundle.js:1
e @ polyfills.2272bcc….bundle.js:1
main.1b9dc37….bundle.js:1 The video load seems to be abnormally long.



Please reply. @Chocobozzz  @Dryusdan

**Comment by Dryusdan** [comment]
wss:// on port 80? 
80 is ws://
443 is wss

ws = websocket
wss websocket secure
same if you call https://site:80

**Comment by shahzaib414** [comment]
So which thing i need to  do

**Comment by Dryusdan** [comment]
what is your config/default.yml && config/production.yml ? (please paste with \``` quote )

**Comment by shahzaib414** [comment]
config/production.yml
listen:
  port: 9000

# Correspond to your reverse proxy "listen" configuration
webserver:
  https: true
  hostname: '62.210.77.240'
  port: 80

# Your database name will be "peertube"+database.suffix
database:
  hostname: 'localhost'
  port: 5432
  suffix: '_prod'
  username: 'peertube'
  password: 'peertube'

# From the project root directory
storage:
  certs: 'certs/'
  videos: 'videos/'
  logs: 'logs/'
  previews: 'previews/'
  thumbnails: 'thumbnails/'
  torrents: 'torrents/'

admin:
  email: 'admin@example.com'

signup:
  enabled: false
**config/defualt**

listen:
  port: 9000

webserver:
  https: false
  hostname: 'localhost'
  port: 9000

# Your database name will be "peertube"+database.suffix
database:
  hostname: 'localhost'
  port: 5432
  suffix: '_dev'
  username: 'peertube'
  password: 'peertube'

# From the project root directory
storage:
  certs: 'certs/'
  videos: 'videos/'
  logs: 'logs/'
  previews: 'previews/'
  thumbnails: 'thumbnails/'
  torrents: 'torrents/'

admin:
  email: 'admin@example.com'

signup:
  enabled: false

**Comment by Dryusdan** [comment]
https false if you use port 80
https true if you use port 443

**Comment by shahzaib414** [comment]
but you said i just need to enable https . don't need to change port  to 443

**Comment by shahzaib414** [comment]
so should i use https true 
port 443 in both config file ?

**Comment by Dryusdan** [comment]
heer...
https://github.com/Chocobozzz/PeerTube/issues/37#issuecomment-312201731
https://github.com/Chocobozzz/PeerTube/issues/37#issuecomment-312200115
https://github.com/Chocobozzz/PeerTube/issues/37#issuecomment-312200115

I don't said that... 🤔 

Whatever, if you would use https, configure your peertube config and your reverse proxy to use https (set tu true) and port (set to 443)

**Comment by shahzaib414** [comment]
hey  i sucessfully installed . but i cannot upload file above 1 gb

**Comment by Dryusdan** [comment]
on your vhost nginx, change your `client_max_body_size` to 1G or another size

**Comment by shahzaib414** [comment]
which file need to edit

**Comment by Chocobozzz** [comment]
@shahzaib414 Make your own search -> https://www.google.fr/search?q=client_max_body_size+nginx&ie=utf-8&oe=utf-8&client=firefox-b&gfe_rd=cr&ei=gzpWWcakAYuA4gT8zJHgCQ
