### ISSUE TITLE
Failed to start: Cannot find module 'node:process'

### ISSUE THREAD

**Issue by Lurkars** [Chocobozzz/PeerTube#5508]
### Describe the current behavior

After upgrading from 4.2.2 to 5.0.1 I got following error on startup.

```
Jan 05 11:09:52 bstly systemd[1]: Started PeerTube daemon.
Jan 05 11:09:53 bstly peertube[1372378]: [tube.bstly.de:443] 2023-01-05 11:09:53.421 error: uncaughtException: Cannot find module 'node:process'
Jan 05 11:09:53 bstly peertube[1372378]: Require stack:
Jan 05 11:09:53 bstly peertube[1372378]: - /var/www/peertube/versions/peertube-v5.0.1/node_modules/@digitalbazaar/http-client/dist/cjs/index.cjs
Jan 05 11:09:53 bstly peertube[1372378]: - /var/www/peertube/versions/peertube-v5.0.1/node_modules/jsonld/lib/documentLoaders/node.js
Jan 05 11:09:53 bstly peertube[1372378]: - /var/www/peertube/versions/peertube-v5.0.1/node_modules/jsonld/lib/platform.js
Jan 05 11:09:53 bstly peertube[1372378]: - /var/www/peertube/versions/peertube-v5.0.1/node_modules/jsonld/lib/jsonld.js
Jan 05 11:09:53 bstly peertube[1372378]: - /var/www/peertube/versions/peertube-v5.0.1/node_modules/jsonld/lib/index.js
Jan 05 11:09:53 bstly peertube[1372378]: - /var/www/peertube/versions/peertube-v5.0.1/dist/server/helpers/custom-jsonld-signature.js
Jan 05 11:09:53 bstly peertube[1372378]: - /var/www/peertube/versions/peertube-v5.0.1/dist/server/helpers/peertube-crypto.js
Jan 05 11:09:53 bstly peertube[1372378]: - /var/www/peertube/versions/peertube-v5.0.1/dist/server/lib/activitypub/send/http.js
Jan 05 11:09:53 bstly peertube[1372378]: - /var/www/peertube/versions/peertube-v5.0.1/dist/server/lib/activitypub/send/index.js
Jan 05 11:09:53 bstly peertube[1372378]: - /var/www/peertube/versions/peertube-v5.0.1/dist/server/models/video/video-channel.js
Jan 05 11:09:53 bstly peertube[1372378]: - /var/www/peertube/versions/peertube-v5.0.1/dist/server/models/redundancy/video-redundancy.js
Jan 05 11:09:53 bstly peertube[1372378]: - /var/www/peertube/versions/peertube-v5.0.1/dist/server/models/video/video-file.js
Jan 05 11:09:53 bstly peertube[1372378]: - /var/www/peertube/versions/peertube-v5.0.1/dist/server/lib/hls.js
Jan 05 11:09:53 bstly peertube[1372378]: - /var/www/peertube/versions/peertube-v5.0.1/dist/server/lib/live/live-segment-sha-store.js
Jan 05 11:09:53 bstly peertube[1372378]: - /var/www/peertube/versions/peertube-v5.0.1/dist/server/lib/live/index.js
Jan 05 11:09:53 bstly peertube[1372378]: - /var/www/peertube/versions/peertube-v5.0.1/dist/server/models/user/user.js
Jan 05 11:09:53 bstly peertube[1372378]: - /var/www/peertube/versions/peertube-v5.0.1/dist/server/lib/live/live-manager.js
Jan 05 11:09:53 bstly peertube[1372378]: - /var/www/peertube/versions/peertube-v5.0.1/dist/server/models/video/video.js
Jan 05 11:09:53 bstly peertube[1372378]: - /var/www/peertube/versions/peertube-v5.0.1/dist/server/models/actor/actor.js
Jan 05 11:09:53 bstly peertube[1372378]: - /var/www/peertube/versions/peertube-v5.0.1/dist/server/models/account/actor-custom-page.js
Jan 05 11:09:53 bstly peertube[1372378]: - /var/www/peertube/versions/peertube-v5.0.1/dist/server/initializers/database.js
Jan 05 11:09:53 bstly peertube[1372378]: - /var/www/peertube/versions/peertube-v5.0.1/dist/server/helpers/database-utils.js
Jan 05 11:09:53 bstly peertube[1372378]: - /var/www/peertube/versions/peertube-v5.0.1/dist/server/models/video/thumbnail.js
Jan 05 11:09:53 bstly peertube[1372378]: - /var/www/peertube/versions/peertube-v5.0.1/dist/server/models/abuse/abuse.js
Jan 05 11:09:53 bstly peertube[1372378]: - /var/www/peertube/versions/peertube-v5.0.1/dist/server/models/abuse/video-comment-abuse.js
Jan 05 11:09:53 bstly peertube[1372378]: - /var/www/peertube/versions/peertube-v5.0.1/dist/server/models/video/video-comment.js
Jan 05 11:09:53 bstly peertube[1372378]: - /var/www/peertube/versions/peertube-v5.0.1/dist/server/lib/activitypub/send/send-delete.js
Jan 05 11:09:53 bstly peertube[1372378]: - /var/www/peertube/versions/peertube-v5.0.1/dist/server/models/account/account.js
Jan 05 11:09:53 bstly peertube[1372378]: - /var/www/peertube/versions/peertube-v5.0.1/dist/server/models/application/application.js
Jan 05 11:09:53 bstly peertube[1372378]: - /var/www/peertube/versions/peertube-v5.0.1/dist/server/initializers/checker-after-init.js
Jan 05 11:09:53 bstly peertube[1372378]: - /var/www/peertube/versions/peertube-v5.0.1/dist/server.js
```

### Steps to reproduce

1.
2.
3.

### Additional information

* PeerTube instance:
  * URL: https://tube.bstly.de
  * Version: v5.0.1
  * NodeJS version: v18.12.1
  * Ffmpeg version: 4.4.3
